---
- name: Copy token file to workers
  ansible.builtin.copy:
    src: static/token_file
    dest: /root/cluster_token_file
    owner: root
    group: root
    mode: '0644'

- name: Joining worker nodes with kubernetes master
  ansible.builtin.shell:
    cmd: |
      kubeadm reset -f
      cat /root/cluster_token_file | tail -2 > out.sh
      sh out.sh
    creates: out.sh

- name: Create manifests folder
  ansible.builtin.file:
    path: "/etc/kubernetes/manifests"
    state: directory
    mode: "600"

