---
- name: Install packages - filesystem
  ansible.builtin.package:
    name:
      - e2fsprogs
      - parted
    state: present

- name: Create partition for perm data
  community.general.parted:
    device: /dev/mmcblk0
    number: 2
    fs_type: ext4
    part_start: 1GiB
    part_end: 100%
    flags: [boot]
    state: present

- name: Fomat perm data partition
  community.general.filesystem:
    dev: /dev/mmcblk0p2
    fstype: ext4
    force: true

- name: Re-mount old data partition
  ansible.posix.mount:
    path: /media/mmcblk0p1
    src: /dev/mmcblk0p1
    opts: rw
    state: remounted

- name: Mount perm data partition
  ansible.posix.mount:
    path: /mnt
    src: /dev/mmcblk0p2
    opts: rw
    fstype: ext4
    state: mounted

- name: Setup new disk as system
  ansible.builtin.command:
    cmd: setup-disk -m sys /mnt
    creates: /mnt/bin/date
  environment:
    FORCE_BOOTFS: 1

- name: Housekeeping - delete old boot
  ansible.builtin.file:
    path: /media/mmcblk0p1/boot
    state: absent

- name: Housekeeping - delete boot/boot
  ansible.builtin.file:
    path: /mnt/boot/boot
    state: absent

- name: Housekeeping - copy boot to first partition
  ansible.builtin.copy:
    src: /mnt/boot
    dest: /media/mmcblk0p1
    mode: preserve
    remote_src: true
    directory_mode: true

- name: Housekeeping - delete boot before symbolic link is created
  ansible.builtin.file:
    path: /mnt/boot
    state: absent

- name: Housekeeping - create media folder
  ansible.builtin.file:
    path: /mnt/media/mmcblk0p1
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Housekeeping - create symbolic link
  ansible.builtin.file:
    dest: /mnt/boot
    src: /media/mmcblk0p1/boot
    state: link
    force: true

- name: Add mountpoints to fstab
  ansible.builtin.shell:
    cmd: |
      echo "/dev/mmcblk0p1 /media/mmcblk0p1 vfat defaults 0 0" >> etc/fstab
      echo "/dev/mmcblk0p1 /media/mmcblk0p1 vfat defaults 0 0" >> /etc/fstab
      sed -i '/cdrom/d' etc/fstab
      sed -i '/floppy/d' etc/fstab
      sed -i '/usbdisk/d' etc/fstab
      touch /mnt/.nvm_mountpoints
      touch /mnt/mnt/.nvm_mountpoints
    chdir: /mnt
    creates: /mnt/.nvm_mountpoints

- name: Enable repositories
  ansible.builtin.replace:
    path: /mnt/etc/apk/repositories
    regexp: '^#(.*\/edge.*)'
    replace: '\1'

- name: Get current cmdline.txt
  ansible.builtin.slurp:
    src: /media/mmcblk0p1/cmdline.txt
  register: cmdline

- name: Update cmdline
  ansible.builtin.template:
    src: cmdline.j2
    dest: /media/mmcblk0p1/cmdline.txt
    mode: 0644
  vars:
    cmdline: "{{ cmdline['content'] | b64decode }}"

- name: Create info file that all file config is ready
  ansible.builtin.file:
    path: /mnt/.nvm_cgroups
    state: touch
    mode: 0644

- name: Copy ssh public keys from overlay to new sys
  ansible.builtin.copy:
    src: /root/.ssh
    dest: /mnt/root/
    mode: preserve
    remote_src: true
    directory_mode: true

- name: Commit changes
  ansible.builtin.shell:
    chdir: /media/mmcblk0p1
    cmd: lbu_commit -d || true

- name: Reboot
  ansible.builtin.reboot:
