---
- name: Install packages for kubernetes
  ansible.builtin.apt:
    update_cache: true
    name:
      - kubectl={{ settings.kubernetes_version }}.*
      - kubelet={{ settings.kubernetes_version }}.*
      - kubeadm={{ settings.kubernetes_version }}.*
    state: present

- name: Download crio tar.gz
  ansible.builtin.get_url:
  # make architecture variable
    url: https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.v{{ settings.kubernetes_version }}.0.tar.gz
    dest: /tmp/crio.tar.gz
    mode: '0755'

- name: Extract crio tar.gz
  ansible.builtin.unarchive:
    src: /tmp/crio.tar.gz
    dest: /tmp
    remote_src: true
    creates: /tmp/cri-o/bin/crio

- name: Install crio
  ansible.builtin.shell:
    cmd: |
      SYSTEMDDIR=/lib/systemd/system
      /tmp/cri-o/install
    chdir: /tmp/cri-o
    creates: /etc/crio/crio.conf
  register: install_crio

- name: Create crio.conf module load
  ansible.builtin.copy:
    src: static/crio.conf
    dest: /etc/modules-load.d/crio.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: create_crio_conf

- name: Create registries.conf
  ansible.builtin.copy:
    src: static/registries.conf
    dest: /etc/containers/registries.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  register: create_registries_conf

- name: Add overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set kernel config params
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: true

- name: Set kernel config params
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: true

- name: Set kernel config params
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: true

- name: Enable service crio
  ansible.builtin.service:
    name: crio
    state: started
    enabled: true

- name: Enable service kubelet
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true

- name: Pull basic images
  ansible.builtin.command:
    cmd: kubeadm config images pull
    creates: /var/lib/containers/storage/overlay-images/images.json
  register: test

# - name: Install helm
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#     dest: /tmp/download.sh
#     mode: '0755'
#   register: download_helm

# - name: Download helm
#   ansible.builtin.shell: /tmp/download.sh
#   when: download_helm is changed
