---
- name: Start Updates
  ansible.builtin.include_tasks: updates.yml
- name: Setup Hostname / Network Packages
  ansible.builtin.include_tasks: networking.yml
- name: Install kubernetes
  ansible.builtin.include_tasks: kubernetes.yml
- name: Mount NFS share
  ansible.builtin.include_tasks: nfs.yml
