---
- name: Restart and Enable service avahi
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted
    enabled: true
  listen: "restart avahi"

- name: Check if base services are started
  ansible.builtin.service:
    name: mountpropagation
    state: started
  listen: "check_mountpropagation_service"
