---
- name: Copy cluster config
  ansible.builtin.copy:
    src: static/clusterconfig.yaml
    dest: "{{ ansible_user_dir }}/clusterconfig.yaml"
    mode: 0600

- name: Initialize cluster
  ansible.builtin.shell:
    cmd: |
      kubeadm reset -f
      kubeadm init --config {{ ansible_user_dir }}/clusterconfig.yaml
    creates: /etc/kubernetes/kubelet.conf
  register: k8sinit_output

- name: Storing Logs and Generated token for nodes config
  ansible.builtin.template:
    src: cluster_join.j2
    dest: cluster_join_file
    mode: 0600
  vars:
    content: '{{ k8sinit_output.stdout }}'
  when: '"token" in k8sinit_output.stdout'

- name: Pulling the token file for setup purposes
  ansible.builtin.fetch:
    flat: true
    src: cluster_join_file
    dest: static/token_file
  when: '"token" in k8sinit_output.stdout'

- name: Save kubeconfig locally
  ansible.builtin.fetch:
    flat: true
    src: /etc/kubernetes/admin.conf
    dest: static/kubectl.conf
    fail_on_missing: true

- name: Create kube folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: 0600

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: static/kubectl.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
