[tool.poetry]
name = "ansible-install"
version = "0.1.0"
description = ""
authors = ["Tobias Klauenberg <toklaui@live.de>"]

[tool.poetry.dependencies]
ansible = "^5.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
