---
- hosts: all
  name: Common Tasks
  vars:
    settings:
      nfs_host: "nfs_host"
      nfs_multi_share_path: "/nfs/path"
      kubernetes_version: "1.28"
  roles:
    - common

- hosts: masters
  name: Configure Kubernetes Master
  roles:
    - kubemaster

- hosts: workers
  name: Let Kube workers join Master
  roles:
    - kubeworkers

- hosts: masters
  name: Start Kubernetes
  roles:
    - basics
